[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && gunicorn wordlist_manager.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/v1/manifest"
restartPolicyType = "ON_FAILURE"
