# Generated by Django 5.2.1 on 2026-02-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('active_word_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], db_index=True, max_length=8)),
                ('file_path', models.CharField(max_length=512)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='words.datasetversion')),
            ],
            options={
                'ordering': ['-dataset_version__version_number', 'export_format'],
                'constraints': [models.UniqueConstraint(fields=('dataset_version', 'export_format'), name='uq_exportartifact_version_format')],
            },
        ),
        migrations.CreateModel(
            name='WordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('sanitized_text', models.CharField(db_index=True, editable=False, max_length=255)),
                ('normalized_text', models.CharField(db_index=True, editable=False, max_length=255)),
                ('word_type', models.CharField(choices=[('guessing', 'Guessing'), ('describing', 'Describing')], max_length=24)),
                ('subcategory', models.CharField(blank=True, max_length=128)),
                ('hint', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='words.category')),
            ],
            options={
                'ordering': ['sanitized_text'],
                'constraints': [models.UniqueConstraint(fields=('normalized_text', 'word_type'), name='uq_wordentry_normalized_word_type')],
            },
        ),
    ]
