# Generated by Django 5.2.1 on 2026-02-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wordentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('word_type', 'guessing')), models.Q(('word_type', 'guessing'), _negated=True), _connector='OR'), name='ck_guessing_requires_category'),
        ),
    ]
