# Generated by Django 5.2.1 on 2026-02-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_seed_default_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StagedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('sanitized_text', models.CharField(db_index=True, editable=False, max_length=255)),
                ('normalized_text', models.CharField(db_index=True, editable=False, max_length=255)),
                ('word_type', models.CharField(choices=[('guessing', 'Guessing'), ('describing', 'Describing')], default='guessing', max_length=24)),
                ('category_name', models.CharField(blank=True, max_length=64)),
                ('subcategory', models.CharField(blank=True, max_length=128)),
                ('hint', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_words', to='words.importbatch')),
                ('resulting_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_origins', to='words.wordentry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staged_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verdict', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=16)),
                ('reporter_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('comment', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('resolution', models.CharField(blank=True, choices=[('keep', 'Keep'), ('deactivate', 'Deactivate'), ('ignore', 'Ignore')], max_length=16)),
                ('manager_note', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_feedback', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='words.wordentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
