# Generated by Django 5.2.1 on 2026-02-28 09:44

import django.db.models.deletion
from django.db import migrations, models


def assign_base_collection(apps, schema_editor):
    Collection = apps.get_model("words", "Collection")
    WordEntry = apps.get_model("words", "WordEntry")
    base, _ = Collection.objects.get_or_create(name="Base", defaults={"is_active": True})
    WordEntry.objects.filter(collection__isnull=True).update(collection=base)


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_importbatch_stagedword_wordfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stagedword',
            name='collection_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='wordentry',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='words.collection'),
        ),
        migrations.RunPython(assign_base_collection, noop),
    ]
