# Generated by Codex on 2026-03-02

from django.db import migrations, models
from django.db.models import Count


def consolidate_word_entries(apps, schema_editor):
    WordEntry = apps.get_model("words", "WordEntry")
    WordFeedback = apps.get_model("words", "WordFeedback")
    StagedWord = apps.get_model("words", "StagedWord")
    Category = apps.get_model("words", "Category")
    fallback_category, _ = Category.objects.get_or_create(name="What", defaults={"is_active": True})

    duplicate_groups = (
        WordEntry.objects.values("normalized_text")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )

    for group in duplicate_groups.iterator():
        rows = list(
            WordEntry.objects.filter(normalized_text=group["normalized_text"]).order_by("created_at", "id")
        )
        if not rows:
            continue

        # Preference rule: keep describing row data when present.
        keep = next((row for row in rows if row.word_type == "describing"), rows[0])
        loser_ids = [row.id for row in rows if row.id != keep.id]
        has_guessing = any(
            (getattr(row, "is_guessing", False) or row.word_type == "guessing")
            for row in rows
        )
        has_describing = any(
            (getattr(row, "is_describing", False) or row.word_type == "describing")
            for row in rows
        )
        if not has_guessing and not has_describing:
            has_guessing = True
        if has_guessing and keep.category_id is None:
            keep.category_id = fallback_category.id

        keep.is_guessing = has_guessing
        keep.is_describing = has_describing
        keep.word_type = "describing" if has_describing else "guessing"
        keep_update_fields = ["is_guessing", "is_describing", "word_type", "updated_at"]
        if has_guessing and keep.category_id == fallback_category.id:
            keep_update_fields.append("category")
        keep.save(update_fields=keep_update_fields)

        if loser_ids:
            WordFeedback.objects.filter(word_id__in=loser_ids).update(word_id=keep.id)
            StagedWord.objects.filter(resulting_word_id__in=loser_ids).update(resulting_word_id=keep.id)
            WordEntry.objects.filter(id__in=loser_ids).delete()

    for row in WordEntry.objects.all().iterator():
        is_guessing = bool(getattr(row, "is_guessing", False) or row.word_type == "guessing")
        is_describing = bool(getattr(row, "is_describing", False) or row.word_type == "describing")
        if not is_guessing and not is_describing:
            is_guessing = True
        category_changed = False
        if is_guessing and row.category_id is None:
            row.category_id = fallback_category.id
            category_changed = True
        canonical = "describing" if is_describing else "guessing"
        if (
            row.is_guessing != is_guessing
            or row.is_describing != is_describing
            or row.word_type != canonical
            or category_changed
        ):
            row.is_guessing = is_guessing
            row.is_describing = is_describing
            row.word_type = canonical
            update_fields = ["is_guessing", "is_describing", "word_type", "updated_at"]
            if category_changed:
                update_fields.append("category")
            row.save(update_fields=update_fields)


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0005_collection_stagedword_collection_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordentry",
            name="is_describing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wordentry",
            name="is_guessing",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(consolidate_word_entries, noop),
        migrations.RemoveConstraint(
            model_name="wordentry",
            name="uq_wordentry_normalized_word_type",
        ),
        migrations.RemoveConstraint(
            model_name="wordentry",
            name="ck_guessing_requires_category",
        ),
        migrations.AddConstraint(
            model_name="wordentry",
            constraint=models.UniqueConstraint(fields=("normalized_text",), name="uq_wordentry_normalized"),
        ),
        migrations.AddConstraint(
            model_name="wordentry",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("is_describing", True)), models.Q(("is_guessing", True)), _connector="OR"),
                name="ck_wordentry_has_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="wordentry",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("is_guessing", False)), models.Q(("category__isnull", False)), _connector="OR"),
                name="ck_guessing_requires_category",
            ),
        ),
    ]
