# Generated by Django 5.2.1 on 2026-03-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_wordentry_multi_type_consolidation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wordentry',
            name='ck_wordentry_has_type',
        ),
        migrations.RemoveConstraint(
            model_name='wordentry',
            name='ck_guessing_requires_category',
        ),
        migrations.AddConstraint(
            model_name='wordentry',
            constraint=models.CheckConstraint(condition=models.Q(('is_guessing', True), ('is_describing', True), _connector='OR'), name='ck_wordentry_has_type'),
        ),
        migrations.AddConstraint(
            model_name='wordentry',
            constraint=models.CheckConstraint(condition=models.Q(('is_guessing', False), ('category__isnull', False), _connector='OR'), name='ck_guessing_requires_category'),
        ),
    ]
