from django.urls import path

from webui.views import (
    apply_validation_action,
    bulk_resolve_feedback,
    bulk_review_staging,
    feedback_home,
    feedback_swipe,
    home,
    manage_ingestion,
    manage_dashboard,
    manage_ai,
    manage_qa,
    manage_jobs,
    manage_settings,
    manage_feedback,
    manage_validation,
    publish_now,
    resolve_feedback,
    review_staging_word,
    run_ai_complete_templates,
    run_ai_generate_words,
    run_manage_check_deploy,
    run_manage_consolidate,
    run_manage_dedupe,
    run_manage_import,
    run_manage_validate,
    staging_dashboard,
    submit_feedback,
    upload_staging_csv,
)

urlpatterns = [
    path("", home, name="home"),
    path("landing/", home, name="landing-home"),
    path("feedback/", feedback_home, name="feedback-home"),
    path("feedback/swipe/", feedback_swipe, name="feedback-swipe"),
    path("feedback/app/", feedback_swipe, name="feedback-app"),
    path("feedback/swipe/app/", feedback_swipe, name="feedback-swipe-app"),
    path("feedback/submit/", submit_feedback, name="submit-feedback"),
    path("manage/", manage_dashboard, name="manage-dashboard"),
    path("manage/ingestion/", manage_ingestion, name="manage-ingestion"),
    path("manage/qa/", manage_qa, name="manage-qa"),
    path("manage/jobs/", manage_jobs, name="manage-jobs"),
    path("manage/settings/", manage_settings, name="manage-settings"),
    path("manage/ai/", manage_ai, name="manage-ai"),
    path("manage/actions/import-source/", run_manage_import, name="manage-action-import"),
    path("manage/actions/dedupe/", run_manage_dedupe, name="manage-action-dedupe"),
    path("manage/actions/consolidate/", run_manage_consolidate, name="manage-action-consolidate"),
    path("manage/actions/validate/", run_manage_validate, name="manage-action-validate"),
    path("manage/actions/check-deploy/", run_manage_check_deploy, name="manage-action-check-deploy"),
    path("manage/actions/ai-complete/", run_ai_complete_templates, name="manage-action-ai-complete"),
    path("manage/actions/ai-generate/", run_ai_generate_words, name="manage-action-ai-generate"),
    path("manage/validation/", manage_validation, name="manage-validation"),
    path("manage/validation/apply/", apply_validation_action, name="apply-validation-action"),
    path("manage/feedback/", manage_feedback, name="manage-feedback"),
    path("manage/feedback/resolve/", resolve_feedback, name="resolve-feedback"),
    path("manage/feedback/bulk-resolve/", bulk_resolve_feedback, name="bulk-resolve-feedback"),
    path("manage/staging/", staging_dashboard, name="staging-dashboard"),
    path("manage/staging/upload/", upload_staging_csv, name="upload-staging-csv"),
    path("manage/staging/review/", review_staging_word, name="review-staging-word"),
    path("manage/staging/bulk-review/", bulk_review_staging, name="bulk-review-staging"),
    path("manage/publish/", publish_now, name="publish-now"),
]
